# Generated by Django 6.0.1 on 2026-04-01 11:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FusionFicha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(choices=[(True, 'Activo'), (False, 'Inactivo')], default=True, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('paciente_ficticio_id', models.IntegerField(blank=True, null=True, verbose_name='ID Paciente Ficticio')),
                ('paciente_real_id', models.IntegerField(blank=True, null=True, verbose_name='ID Paciente Real')),
                ('rut_ficticio', models.CharField(blank=True, max_length=100, null=True, verbose_name='RUT Ficticio')),
                ('rut_real', models.CharField(blank=True, max_length=100, null=True, verbose_name='RUT Real')),
                ('nombres', models.CharField(max_length=200, verbose_name='Nombres')),
                ('apellidos', models.CharField(max_length=200, verbose_name='Apellidos')),
                ('nombres_real', models.CharField(max_length=200, verbose_name='Nombres Reales')),
                ('apellidos_real', models.CharField(max_length=200, verbose_name='Apellidos Reales')),
                ('sexo', models.CharField(choices=[('NO INFORMADO', 'NO INFORMADO'), ('M', 'MASCULINO'), ('F', 'FEMENINO')], default='NO INFORMADO', max_length=50, verbose_name='Sexo')),
                ('numero_ficha_sistema', models.IntegerField(blank=True, null=True, verbose_name='Número Ficha Sistema')),
                ('numero_ficha_sistema_real', models.IntegerField(blank=True, null=True, verbose_name='Número Ficha Sistema Real')),
                ('fecha_creacion_anterior', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Creación Anterior')),
                ('fecha_creacion_actual', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Creación Actual en Sistema')),
                ('se_queda_primera_ficha', models.BooleanField(default=False, verbose_name='Se queda la primera ficha')),
                ('se_queda_segunda_ficha', models.BooleanField(default=False, verbose_name='Se queda la segunda ficha')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado Por')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado Por')),
            ],
            options={
                'verbose_name': 'Fusión de Ficha',
                'verbose_name_plural': 'Fusiones de Fichas',
            },
        ),
    ]
