# Generated by Django 6.0.1 on 2026-04-01 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establecimientos', '0003_alter_servicioclinico_options'),
        ('fichas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fusionficha',
            name='establecimiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fusiones_fichas', to='establecimientos.establecimiento', verbose_name='Establecimiento'),
        ),
    ]
