# Generated by Django 6.0.1 on 2026-02-20 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalrole',
            name='movimiento_ficha_controlado',
            field=models.IntegerField(choices=[(0, 'Sin acceso'), (1, 'Solo lectura'), (2, 'Lectura y escritura')], default=0),
        ),
        migrations.AddField(
            model_name='role',
            name='movimiento_ficha_controlado',
            field=models.IntegerField(choices=[(0, 'Sin acceso'), (1, 'Solo lectura'), (2, 'Lectura y escritura')], default=0),
        ),
    ]
