# Generated by Django 6.0 on 2025-12-25 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_historicaluser_establecimiento_user_establecimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalrole',
            name='reportes',
            field=models.IntegerField(choices=[(0, 'Sin acceso'), (1, 'Solo lectura'), (2, 'Lectura y escritura')], default=0),
        ),
        migrations.AddField(
            model_name='role',
            name='reportes',
            field=models.IntegerField(choices=[(0, 'Sin acceso'), (1, 'Solo lectura'), (2, 'Lectura y escritura')], default=0),
        ),
    ]
