# Generated by Django 6.0.1 on 2026-03-03 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_historicalrole_movimiento_ficha_controlado_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['first_name'], 'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
    ]
