# Generated by Django 6.0 on 2025-12-30 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_historicalrole_reportes_role_reportes'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalrole',
            name='colores_sector',
            field=models.IntegerField(choices=[(0, 'Sin acceso'), (1, 'Solo lectura'), (2, 'Lectura y escritura')], default=0),
        ),
        migrations.AddField(
            model_name='role',
            name='colores_sector',
            field=models.IntegerField(choices=[(0, 'Sin acceso'), (1, 'Solo lectura'), (2, 'Lectura y escritura')], default=0),
        ),
    ]
