# Generated by Django 6.0.1 on 2026-04-07 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_options'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userrole',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='userrole',
            name='role_id',
        ),
        migrations.RemoveField(
            model_name='userrole',
            name='user_id',
        ),
        migrations.DeleteModel(
            name='HistoricalUserRole',
        ),
        migrations.DeleteModel(
            name='UserRole',
        ),
    ]
