# Generated by Django 6.0 on 2026-01-05 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_historicalrole_colores_sector_role_colores_sector'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalrole',
            name='usuarios',
            field=models.IntegerField(choices=[(0, 'Sin acceso'), (1, 'Solo lectura'), (2, 'Lectura y escritura')], default=0),
        ),
        migrations.AddField(
            model_name='role',
            name='usuarios',
            field=models.IntegerField(choices=[(0, 'Sin acceso'), (1, 'Solo lectura'), (2, 'Lectura y escritura')], default=0),
        ),
    ]
