# Generated by Django 6.0.1 on 2026-04-07 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_userrole_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluser',
            name='rol',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='users.role', verbose_name='Rol'),
        ),
        migrations.AddField(
            model_name='user',
            name='rol',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.role', verbose_name='Rol'),
        ),
    ]
