# Generated by Django 6.0 on 2026-01-05 01:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establecimientos', '0005_alter_establecimiento_direccion_and_more'),
        ('users', '0005_historicalrole_usuarios_role_usuarios'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalrole',
            name='establecimiento',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='establecimientos.establecimiento'),
        ),
        migrations.AddField(
            model_name='role',
            name='establecimiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='establecimientos.establecimiento'),
        ),
    ]
