# Generated by Django 6.0.1 on 2026-04-20 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_historicaluser_rol_user_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalrole',
            name='status',
            field=models.BooleanField(choices=[(True, 'Activo'), (False, 'Inactivo')], default=True, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='role',
            name='status',
            field=models.BooleanField(choices=[(True, 'Activo'), (False, 'Inactivo')], default=True, verbose_name='Estado'),
        ),
    ]
