# Generated by Django 6.0.1 on 2026-05-06 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_historicalrole_status_role_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluser',
            name='is_creator_system',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_creator_system',
            field=models.BooleanField(default=False),
        ),
    ]
