# Generated by Django 6.0 on 2025-12-23 18:38

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establecimientos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalSector',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('status', models.BooleanField(choices=[(True, 'Activo'), (False, 'Inactivo')], default=True, verbose_name='Estado')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Fecha Creación')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='Última Actualización')),
                ('codigo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Código del Sector')),
                ('color', models.CharField(blank=True, default='NO INFORMADO', max_length=100, null=True, verbose_name='Color del Sector')),
                ('observacion', models.TextField(blank=True, choices=[('ROJO', 'Rojo'), ('AZUL', 'Azul'), ('VERDE', 'Verde'), ('AMARILLO', 'Amarillo'), ('NARANJA', 'Naranja'), ('MORADO', 'Morado'), ('ROSA', 'Rosa'), ('MARRÓN', 'Marrón'), ('GRIS', 'Gris'), ('NEGRO', 'Negro'), ('CIAN', 'Cian'), ('MAGENTA', 'Magenta'), ('LIMA', 'Lima'), ('VERDE AZULADO', 'Verde azulado'), ('AZUL MARINO', 'Azul marino'), ('GRANATE', 'Granate'), ('OLIVA', 'Oliva'), ('DORADO', 'Dorado'), ('PLATEADO', 'Plateado'), ('BEIGE', 'Beige')], null=True, verbose_name='Observaciones')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Creado Por')),
                ('establecimiento', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='establecimientos.establecimiento', verbose_name='Establecimiento')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado Por')),
            ],
            options={
                'verbose_name': 'historical Sector',
                'verbose_name_plural': 'historical Sectores',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalServicioClinico',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('status', models.BooleanField(choices=[(True, 'Activo'), (False, 'Inactivo')], default=True, verbose_name='Estado')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Fecha Creación')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='Última Actualización')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('tiempo_horas', models.IntegerField(blank=True, null=True, verbose_name='Tiempo en horas')),
                ('correo_jefe', models.EmailField(blank=True, max_length=100, null=True, verbose_name='Correo del jefe a cargo')),
                ('telefono', models.CharField(blank=True, max_length=15, null=True, verbose_name='Teléfono')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Creado Por')),
                ('establecimiento', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='establecimientos.establecimiento', verbose_name='Establecimiento')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado Por')),
            ],
            options={
                'verbose_name': 'historical Servicio Clínico',
                'verbose_name_plural': 'historical Servicios Clínicos',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(choices=[(True, 'Activo'), (False, 'Inactivo')], default=True, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('codigo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Código del Sector')),
                ('color', models.CharField(blank=True, default='NO INFORMADO', max_length=100, null=True, verbose_name='Color del Sector')),
                ('observacion', models.TextField(blank=True, choices=[('ROJO', 'Rojo'), ('AZUL', 'Azul'), ('VERDE', 'Verde'), ('AMARILLO', 'Amarillo'), ('NARANJA', 'Naranja'), ('MORADO', 'Morado'), ('ROSA', 'Rosa'), ('MARRÓN', 'Marrón'), ('GRIS', 'Gris'), ('NEGRO', 'Negro'), ('CIAN', 'Cian'), ('MAGENTA', 'Magenta'), ('LIMA', 'Lima'), ('VERDE AZULADO', 'Verde azulado'), ('AZUL MARINO', 'Azul marino'), ('GRANATE', 'Granate'), ('OLIVA', 'Oliva'), ('DORADO', 'Dorado'), ('PLATEADO', 'Plateado'), ('BEIGE', 'Beige')], null=True, verbose_name='Observaciones')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado Por')),
                ('establecimiento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sector_establecimiento', to='establecimientos.establecimiento', verbose_name='Establecimiento')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado Por')),
            ],
            options={
                'verbose_name': 'Sector',
                'verbose_name_plural': 'Sectores',
            },
        ),
        migrations.CreateModel(
            name='ServicioClinico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(choices=[(True, 'Activo'), (False, 'Inactivo')], default=True, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('tiempo_horas', models.IntegerField(blank=True, null=True, verbose_name='Tiempo en horas')),
                ('correo_jefe', models.EmailField(blank=True, max_length=100, null=True, verbose_name='Correo del jefe a cargo')),
                ('telefono', models.CharField(blank=True, max_length=15, null=True, verbose_name='Teléfono')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado Por')),
                ('establecimiento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servicios_clinicos_establecimiento', to='establecimientos.establecimiento', verbose_name='Establecimiento')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado Por')),
            ],
            options={
                'verbose_name': 'Servicio Clínico',
                'verbose_name_plural': 'Servicios Clínicos',
            },
        ),
    ]
