# Generated by Django 6.0.1 on 2026-03-03 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('establecimientos', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicioclinico',
            options={'ordering': ['nombre'], 'verbose_name': 'Servicio Clínico', 'verbose_name_plural': 'Servicios Clínicos'},
        ),
    ]
