# Generated by Django 6.0 on 2025-12-29 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establecimientos', '0003_color_historicalcolor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsector',
            name='color',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='establecimientos.color', verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='sector',
            name='color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='establecimientos.color', verbose_name='Color'),
        ),
    ]
