# Generated by Django 6.0 on 2026-01-05 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establecimientos', '0005_alter_establecimiento_direccion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalservicioclinico',
            name='codigo',
            field=models.IntegerField(blank=True, null=True, verbose_name='Código'),
        ),
        migrations.AddField(
            model_name='servicioclinico',
            name='codigo',
            field=models.IntegerField(blank=True, null=True, verbose_name='Código'),
        ),
    ]
