# Generated by Django 6.0 on 2026-01-07 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establecimientos', '0006_historicalservicioclinico_codigo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsector',
            name='observacion',
            field=models.TextField(blank=True, null=True, verbose_name='Observaciones'),
        ),
        migrations.AlterField(
            model_name='sector',
            name='observacion',
            field=models.TextField(blank=True, null=True, verbose_name='Observaciones'),
        ),
    ]
