"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

from config.db import MYSQL

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def env_bool(name, default=False):
    value = os.getenv(name)
    if value is None:
        return default
    return value.lower() in ('1', 'true', 'yes', 'on')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-8w2znvem)pk426yza$51dk)d(^u+zt*9mx87^6u!-hx97-7e_p')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env_bool('DEBUG', True)

ALLOWED_HOSTS = [host.strip() for host in os.getenv('ALLOWED_HOSTS', '10.8.85.141,127.0.0.1,localhost').split(',') if host.strip()]
CSRF_TRUSTED_ORIGINS = [origin.strip() for origin in os.getenv('CSRF_TRUSTED_ORIGINS', 'http://10.8.85.141,http://127.0.0.1,http://localhost').split(',') if origin.strip()]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'simple_history',
    'import_export',
    'users',
    'core',
    'geografia',
    'establecimientos',
    'personas',
    'clinica',
    'reports',
    'fichas',
    'respaldos',
]

AUTH_USER_MODEL = 'users.User'
FORCE_SCRIPT_NAME = os.getenv('FORCE_SCRIPT_NAME') or None
LOGIN_URL = os.getenv('LOGIN_URL', '/kardex/login/')
LOGIN_REDIRECT_URL = os.getenv('LOGIN_REDIRECT_URL', '/kardex/dashboard/')
LOGOUT_REDIRECT_URL = os.getenv('LOGOUT_REDIRECT_URL', '/kardex/login/')

SIMPLE_HISTORY_HISTORY_ID_USE_UUID = env_bool('SIMPLE_HISTORY_HISTORY_ID_USE_UUID', False)

X_FRAME_OPTIONS = os.getenv('X_FRAME_OPTIONS', 'ALLOWALL')

CSRF_COOKIE_SAMESITE = os.getenv('CSRF_COOKIE_SAMESITE', 'None')
SESSION_COOKIE_SAMESITE = os.getenv('SESSION_COOKIE_SAMESITE', 'None')

SESSION_COOKIE_NAME = os.getenv('SESSION_COOKIE_NAME', 'kardex_sessionid')
CSRF_COOKIE_NAME = os.getenv('CSRF_COOKIE_NAME', 'kardex_csrftoken')

SESSION_COOKIE_PATH = os.getenv('SESSION_COOKIE_PATH', '/')
CSRF_COOKIE_PATH = os.getenv('CSRF_COOKIE_PATH', '/')

CSRF_COOKIE_SECURE = env_bool('CSRF_COOKIE_SECURE', True)
SESSION_COOKIE_SECURE = env_bool('SESSION_COOKIE_SECURE', True)

USE_X_FORWARDED_HOST = env_bool('USE_X_FORWARDED_HOST', True)

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    #'core.middleware.maintenance.MaintenanceModeMiddleware',
    #'users.middleware.login_required.LoginRequiredMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'users.middleware.user_roles.UserRolesMiddleware',
    #'users.middleware.roles_permissions.RolePermissionMiddleware',
    #'core.middleware.establecimiento_required.EstablecimientoRequiredMiddleware',
    'simple_history.middleware.HistoryRequestMiddleware',

]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'users.context_processors.permissions.permisos_to_template',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'
SIMPLE_HISTORY_ENABLED = env_bool('SIMPLE_HISTORY_ENABLED', True)

# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = MYSQL

# MANTENIMIENTO
MAINTENANCE_MODE = env_bool('MAINTENANCE_MODE', False)

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = os.getenv('LANGUAGE_CODE', 'es-es')

TIME_ZONE = os.getenv('TIME_ZONE', 'America/Santiago')

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = os.getenv('STATIC_URL', '/kardex/static/')

STATICFILES_DIRS = [
    BASE_DIR / 'static'
]

STATIC_ROOT = BASE_DIR / 'staticfiles'