# Generated by Django 6.0 on 2025-12-23 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geografia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comuna',
            name='codigo',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Código de Comuna'),
        ),
        migrations.AlterField(
            model_name='historicalcomuna',
            name='codigo',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Código de Comuna'),
        ),
    ]
