# Generated by Django 6.0 on 2026-01-20 19:20

import simple_history.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ficha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(choices=[(True, 'Activo'), (False, 'Inactivo')], default=True, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('numero_ficha_sistema', models.IntegerField(blank=True, null=True, verbose_name='Número de Ficha')),
                ('numero_ficha_tarjeta', models.IntegerField(blank=True, null=True, verbose_name='Número de Ficha Tarjeta')),
                ('numero_ficha_respaldo', models.IntegerField(blank=True, null=True, verbose_name='Número de Ficha Respaldo')),
                ('pasivado', models.BooleanField(default=False, verbose_name='Pasivado')),
                ('observacion', models.TextField(blank=True, null=True, verbose_name='Observación')),
                ('fecha_creacion_anterior', models.DateTimeField(blank=True, null=True)),
                ('fecha_mov', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Movimiento')),
            ],
            options={
                'verbose_name': 'Ficha',
                'verbose_name_plural': 'Fichas',
            },
        ),
        migrations.CreateModel(
            name='HistoricalFicha',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('status', models.BooleanField(choices=[(True, 'Activo'), (False, 'Inactivo')], default=True, verbose_name='Estado')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Fecha Creación')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='Última Actualización')),
                ('numero_ficha_sistema', models.IntegerField(blank=True, null=True, verbose_name='Número de Ficha')),
                ('numero_ficha_tarjeta', models.IntegerField(blank=True, null=True, verbose_name='Número de Ficha Tarjeta')),
                ('numero_ficha_respaldo', models.IntegerField(blank=True, null=True, verbose_name='Número de Ficha Respaldo')),
                ('pasivado', models.BooleanField(default=False, verbose_name='Pasivado')),
                ('observacion', models.TextField(blank=True, null=True, verbose_name='Observación')),
                ('fecha_creacion_anterior', models.DateTimeField(blank=True, null=True)),
                ('fecha_mov', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Movimiento')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical Ficha',
                'verbose_name_plural': 'historical Fichas',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalMovimientoFicha',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('status', models.BooleanField(choices=[(True, 'Activo'), (False, 'Inactivo')], default=True, verbose_name='Estado')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Fecha Creación')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='Última Actualización')),
                ('fecha_envio', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Envío')),
                ('fecha_recepcion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Recepción')),
                ('fecha_traspaso', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Traspaso')),
                ('observacion_envio', models.TextField(blank=True, null=True, verbose_name='Observación de Envío')),
                ('observacion_recepcion', models.TextField(blank=True, null=True, verbose_name='Observación de Recepción')),
                ('observacion_traspaso', models.TextField(blank=True, null=True, verbose_name='Observación de Traspaso')),
                ('estado_envio', models.CharField(blank=True, choices=[('ENVIADO', 'Enviado'), ('RECIBIDO', 'Recibido'), ('EN ESPERA', 'En Espera'), ('TRASPASDO', 'Traspasado'), ('SIN TRASPASO', 'Sin Traspaso')], default='ENVIADO', max_length=50, null=True, verbose_name='Estado de Envío')),
                ('estado_recepcion', models.CharField(blank=True, choices=[('ENVIADO', 'Enviado'), ('RECIBIDO', 'Recibido'), ('EN ESPERA', 'En Espera'), ('TRASPASDO', 'Traspasado'), ('SIN TRASPASO', 'Sin Traspaso')], default='EN ESPERA', max_length=50, null=True, verbose_name='Estado de Recepción')),
                ('estado_traspaso', models.CharField(blank=True, choices=[('ENVIADO', 'Enviado'), ('RECIBIDO', 'Recibido'), ('EN ESPERA', 'En Espera'), ('TRASPASDO', 'Traspasado'), ('SIN TRASPASO', 'Sin Traspaso')], default='SIN TRASPASO', max_length=50, null=True, verbose_name='Estado de Traspaso')),
                ('rut_anterior', models.CharField(blank=True, default='SIN RUT', max_length=50, null=True, verbose_name='RUT Anterior del Usuario')),
                ('rut_anterior_profesional', models.CharField(blank=True, default='SIN RUT', max_length=50, null=True, verbose_name='RUT Anterior del Profesional')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical Movimiento Ficha',
                'verbose_name_plural': 'historical Movimientos Fichas',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='MovimientoFicha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(choices=[(True, 'Activo'), (False, 'Inactivo')], default=True, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('fecha_envio', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Envío')),
                ('fecha_recepcion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Recepción')),
                ('fecha_traspaso', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Traspaso')),
                ('observacion_envio', models.TextField(blank=True, null=True, verbose_name='Observación de Envío')),
                ('observacion_recepcion', models.TextField(blank=True, null=True, verbose_name='Observación de Recepción')),
                ('observacion_traspaso', models.TextField(blank=True, null=True, verbose_name='Observación de Traspaso')),
                ('estado_envio', models.CharField(blank=True, choices=[('ENVIADO', 'Enviado'), ('RECIBIDO', 'Recibido'), ('EN ESPERA', 'En Espera'), ('TRASPASDO', 'Traspasado'), ('SIN TRASPASO', 'Sin Traspaso')], default='ENVIADO', max_length=50, null=True, verbose_name='Estado de Envío')),
                ('estado_recepcion', models.CharField(blank=True, choices=[('ENVIADO', 'Enviado'), ('RECIBIDO', 'Recibido'), ('EN ESPERA', 'En Espera'), ('TRASPASDO', 'Traspasado'), ('SIN TRASPASO', 'Sin Traspaso')], default='EN ESPERA', max_length=50, null=True, verbose_name='Estado de Recepción')),
                ('estado_traspaso', models.CharField(blank=True, choices=[('ENVIADO', 'Enviado'), ('RECIBIDO', 'Recibido'), ('EN ESPERA', 'En Espera'), ('TRASPASDO', 'Traspasado'), ('SIN TRASPASO', 'Sin Traspaso')], default='SIN TRASPASO', max_length=50, null=True, verbose_name='Estado de Traspaso')),
                ('rut_anterior', models.CharField(blank=True, default='SIN RUT', max_length=50, null=True, verbose_name='RUT Anterior del Usuario')),
                ('rut_anterior_profesional', models.CharField(blank=True, default='SIN RUT', max_length=50, null=True, verbose_name='RUT Anterior del Profesional')),
            ],
            options={
                'verbose_name': 'Movimiento Ficha',
                'verbose_name_plural': 'Movimientos Fichas',
            },
        ),
    ]
