# Generated by Django 6.0 on 2026-01-05 17:41

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0001_initial'),
        ('establecimientos', '0006_historicalservicioclinico_codigo_and_more'),
        ('personas', '0007_historicalpaciente_id_anterior_paciente_id_anterior'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalMovimientoFicha',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('status', models.BooleanField(choices=[(True, 'Activo'), (False, 'Inactivo')], default=True, verbose_name='Estado')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Fecha Creación')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='Última Actualización')),
                ('fecha_envio', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Envío')),
                ('fecha_recepcion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Recepción')),
                ('fecha_traspaso', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Traspaso')),
                ('observacion_envio', models.TextField(blank=True, null=True, verbose_name='Observación de Envío')),
                ('observacion_recepcion', models.TextField(blank=True, null=True, verbose_name='Observación de Recepción')),
                ('observacion_traspaso', models.TextField(blank=True, null=True, verbose_name='Observación de Traspaso')),
                ('estado_envio', models.CharField(blank=True, choices=[('ENVIADO', 'Enviado'), ('RECIBIDO', 'Recibido'), ('EN ESPERA', 'En Espera'), ('TRASPASDO', 'Traspasado'), ('SIN TRASPASO', 'Sin Traspaso')], default='ENVIADO', max_length=50, null=True, verbose_name='Estado de Envío')),
                ('estado_recepcion', models.CharField(blank=True, choices=[('ENVIADO', 'Enviado'), ('RECIBIDO', 'Recibido'), ('EN ESPERA', 'En Espera'), ('TRASPASDO', 'Traspasado'), ('SIN TRASPASO', 'Sin Traspaso')], default='EN ESPERA', max_length=50, null=True, verbose_name='Estado de Recepción')),
                ('estado_traspaso', models.CharField(blank=True, choices=[('ENVIADO', 'Enviado'), ('RECIBIDO', 'Recibido'), ('EN ESPERA', 'En Espera'), ('TRASPASDO', 'Traspasado'), ('SIN TRASPASO', 'Sin Traspaso')], default='SIN TRASPASO', max_length=50, null=True, verbose_name='Estado de Traspaso')),
                ('rut_anterior', models.CharField(blank=True, default='SIN RUT', max_length=50, null=True, verbose_name='RUT Anterior del Usuario')),
                ('rut_anterior_profesional', models.CharField(blank=True, default='SIN RUT', max_length=50, null=True, verbose_name='RUT Anterior del Profesional')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Creado Por')),
                ('establecimiento', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='establecimientos.establecimiento', verbose_name='Establecimiento')),
                ('ficha', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='clinica.ficha', verbose_name='Ficha')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('profesional_envio', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='personas.profesional', verbose_name='Profesional Envio')),
                ('profesional_recepcion', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='personas.profesional', verbose_name='Profesional Recepcion')),
                ('profesional_traspaso', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='personas.profesional', verbose_name='Profesional Recepcion')),
                ('servicio_clinico_envio', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='establecimientos.servicioclinico', verbose_name='Servicio Clínico de Envío')),
                ('servicio_clinico_recepcion', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='establecimientos.servicioclinico', verbose_name='Servicio Clínico de Recepción')),
                ('servicio_clinico_traspaso', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='establecimientos.servicioclinico', verbose_name='Servicio Clínico de Traspaso')),
                ('updated_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado Por')),
                ('usuario_envio', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Envio')),
                ('usuario_envio_anterior', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='personas.usuarioanterior', verbose_name='Usuario Envio Anterior')),
                ('usuario_recepcion', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Recepcion')),
                ('usuario_recepcion_anterior', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='personas.usuarioanterior', verbose_name='Usuario Recepcion Anterior')),
                ('usuario_traspaso', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Traspaso')),
            ],
            options={
                'verbose_name': 'historical Movimiento Ficha',
                'verbose_name_plural': 'historical Movimientos Fichas',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='MovimientoFicha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(choices=[(True, 'Activo'), (False, 'Inactivo')], default=True, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('fecha_envio', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Envío')),
                ('fecha_recepcion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Recepción')),
                ('fecha_traspaso', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Traspaso')),
                ('observacion_envio', models.TextField(blank=True, null=True, verbose_name='Observación de Envío')),
                ('observacion_recepcion', models.TextField(blank=True, null=True, verbose_name='Observación de Recepción')),
                ('observacion_traspaso', models.TextField(blank=True, null=True, verbose_name='Observación de Traspaso')),
                ('estado_envio', models.CharField(blank=True, choices=[('ENVIADO', 'Enviado'), ('RECIBIDO', 'Recibido'), ('EN ESPERA', 'En Espera'), ('TRASPASDO', 'Traspasado'), ('SIN TRASPASO', 'Sin Traspaso')], default='ENVIADO', max_length=50, null=True, verbose_name='Estado de Envío')),
                ('estado_recepcion', models.CharField(blank=True, choices=[('ENVIADO', 'Enviado'), ('RECIBIDO', 'Recibido'), ('EN ESPERA', 'En Espera'), ('TRASPASDO', 'Traspasado'), ('SIN TRASPASO', 'Sin Traspaso')], default='EN ESPERA', max_length=50, null=True, verbose_name='Estado de Recepción')),
                ('estado_traspaso', models.CharField(blank=True, choices=[('ENVIADO', 'Enviado'), ('RECIBIDO', 'Recibido'), ('EN ESPERA', 'En Espera'), ('TRASPASDO', 'Traspasado'), ('SIN TRASPASO', 'Sin Traspaso')], default='SIN TRASPASO', max_length=50, null=True, verbose_name='Estado de Traspaso')),
                ('rut_anterior', models.CharField(blank=True, default='SIN RUT', max_length=50, null=True, verbose_name='RUT Anterior del Usuario')),
                ('rut_anterior_profesional', models.CharField(blank=True, default='SIN RUT', max_length=50, null=True, verbose_name='RUT Anterior del Profesional')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado Por')),
                ('establecimiento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_fichas_establecimientos', to='establecimientos.establecimiento', verbose_name='Establecimiento')),
                ('ficha', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clinica.ficha', verbose_name='Ficha')),
                ('profesional_envio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_enviados_profesionales', to='personas.profesional', verbose_name='Profesional Envio')),
                ('profesional_recepcion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_recepcionados_profesionales', to='personas.profesional', verbose_name='Profesional Recepcion')),
                ('profesional_traspaso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_traspaso_profesionales', to='personas.profesional', verbose_name='Profesional Recepcion')),
                ('servicio_clinico_envio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='envios_desde_este_servicio', to='establecimientos.servicioclinico', verbose_name='Servicio Clínico de Envío')),
                ('servicio_clinico_recepcion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recepciones_en_este_servicio', to='establecimientos.servicioclinico', verbose_name='Servicio Clínico de Recepción')),
                ('servicio_clinico_traspaso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='traspaso_en_este_servicio', to='establecimientos.servicioclinico', verbose_name='Servicio Clínico de Traspaso')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado Por')),
                ('usuario_envio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_enviados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Envio')),
                ('usuario_envio_anterior', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_enviados_anterior', to='personas.usuarioanterior', verbose_name='Usuario Envio Anterior')),
                ('usuario_recepcion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_recepcionados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Recepcion')),
                ('usuario_recepcion_anterior', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_recepcionados_anterior', to='personas.usuarioanterior', verbose_name='Usuario Recepcion Anterior')),
                ('usuario_traspaso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_traspasados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Traspaso')),
            ],
            options={
                'verbose_name': 'Movimiento Ficha',
                'verbose_name_plural': 'Movimientos Fichas',
            },
        ),
    ]
