# Generated by Django 6.0 on 2026-01-20 19:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinica', '0001_initial'),
        ('establecimientos', '0001_initial'),
        ('personas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ficha',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado Por'),
        ),
        migrations.AddField(
            model_name='ficha',
            name='establecimiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fichas_establecimientos', to='establecimientos.establecimiento', verbose_name='Establecimiento'),
        ),
        migrations.AddField(
            model_name='ficha',
            name='paciente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fichas_pacientes', to='personas.paciente', verbose_name='Paciente'),
        ),
        migrations.AddField(
            model_name='ficha',
            name='sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fichas_sectores', to='establecimientos.sector', verbose_name='Sector'),
        ),
        migrations.AddField(
            model_name='ficha',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado Por'),
        ),
        migrations.AddField(
            model_name='ficha',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fichas_usuarios', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='historicalficha',
            name='created_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Creado Por'),
        ),
        migrations.AddField(
            model_name='historicalficha',
            name='establecimiento',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='establecimientos.establecimiento', verbose_name='Establecimiento'),
        ),
        migrations.AddField(
            model_name='historicalficha',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalficha',
            name='paciente',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='personas.paciente', verbose_name='Paciente'),
        ),
        migrations.AddField(
            model_name='historicalficha',
            name='sector',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='establecimientos.sector', verbose_name='Sector'),
        ),
        migrations.AddField(
            model_name='historicalficha',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado Por'),
        ),
        migrations.AddField(
            model_name='historicalficha',
            name='usuario',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='historicalmovimientoficha',
            name='created_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Creado Por'),
        ),
        migrations.AddField(
            model_name='historicalmovimientoficha',
            name='establecimiento',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='establecimientos.establecimiento', verbose_name='Establecimiento'),
        ),
        migrations.AddField(
            model_name='historicalmovimientoficha',
            name='ficha',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='clinica.ficha', verbose_name='Ficha'),
        ),
        migrations.AddField(
            model_name='historicalmovimientoficha',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalmovimientoficha',
            name='profesional_envio',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='personas.profesional', verbose_name='Profesional Envio'),
        ),
        migrations.AddField(
            model_name='historicalmovimientoficha',
            name='profesional_recepcion',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='personas.profesional', verbose_name='Profesional Recepcion'),
        ),
        migrations.AddField(
            model_name='historicalmovimientoficha',
            name='profesional_traspaso',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='personas.profesional', verbose_name='Profesional Recepcion'),
        ),
        migrations.AddField(
            model_name='historicalmovimientoficha',
            name='servicio_clinico_envio',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='establecimientos.servicioclinico', verbose_name='Servicio Clínico de Envío'),
        ),
        migrations.AddField(
            model_name='historicalmovimientoficha',
            name='servicio_clinico_recepcion',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='establecimientos.servicioclinico', verbose_name='Servicio Clínico de Recepción'),
        ),
        migrations.AddField(
            model_name='historicalmovimientoficha',
            name='servicio_clinico_traspaso',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='establecimientos.servicioclinico', verbose_name='Servicio Clínico de Traspaso'),
        ),
        migrations.AddField(
            model_name='historicalmovimientoficha',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado Por'),
        ),
        migrations.AddField(
            model_name='historicalmovimientoficha',
            name='usuario_envio',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Envio'),
        ),
        migrations.AddField(
            model_name='historicalmovimientoficha',
            name='usuario_envio_anterior',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='personas.usuarioanterior', verbose_name='Usuario Envio Anterior'),
        ),
        migrations.AddField(
            model_name='historicalmovimientoficha',
            name='usuario_recepcion',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Recepcion'),
        ),
        migrations.AddField(
            model_name='historicalmovimientoficha',
            name='usuario_recepcion_anterior',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='personas.usuarioanterior', verbose_name='Usuario Recepcion Anterior'),
        ),
        migrations.AddField(
            model_name='historicalmovimientoficha',
            name='usuario_traspaso',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Traspaso'),
        ),
        migrations.AddField(
            model_name='movimientoficha',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado Por'),
        ),
        migrations.AddField(
            model_name='movimientoficha',
            name='establecimiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_fichas_establecimientos', to='establecimientos.establecimiento', verbose_name='Establecimiento'),
        ),
        migrations.AddField(
            model_name='movimientoficha',
            name='ficha',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clinica.ficha', verbose_name='Ficha'),
        ),
        migrations.AddField(
            model_name='movimientoficha',
            name='profesional_envio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_enviados_profesionales', to='personas.profesional', verbose_name='Profesional Envio'),
        ),
        migrations.AddField(
            model_name='movimientoficha',
            name='profesional_recepcion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_recepcionados_profesionales', to='personas.profesional', verbose_name='Profesional Recepcion'),
        ),
        migrations.AddField(
            model_name='movimientoficha',
            name='profesional_traspaso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_traspaso_profesionales', to='personas.profesional', verbose_name='Profesional Recepcion'),
        ),
        migrations.AddField(
            model_name='movimientoficha',
            name='servicio_clinico_envio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='envios_desde_este_servicio', to='establecimientos.servicioclinico', verbose_name='Servicio Clínico de Envío'),
        ),
        migrations.AddField(
            model_name='movimientoficha',
            name='servicio_clinico_recepcion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recepciones_en_este_servicio', to='establecimientos.servicioclinico', verbose_name='Servicio Clínico de Recepción'),
        ),
        migrations.AddField(
            model_name='movimientoficha',
            name='servicio_clinico_traspaso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='traspaso_en_este_servicio', to='establecimientos.servicioclinico', verbose_name='Servicio Clínico de Traspaso'),
        ),
        migrations.AddField(
            model_name='movimientoficha',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado Por'),
        ),
        migrations.AddField(
            model_name='movimientoficha',
            name='usuario_envio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_enviados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Envio'),
        ),
        migrations.AddField(
            model_name='movimientoficha',
            name='usuario_envio_anterior',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_enviados_anterior', to='personas.usuarioanterior', verbose_name='Usuario Envio Anterior'),
        ),
        migrations.AddField(
            model_name='movimientoficha',
            name='usuario_recepcion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_recepcionados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Recepcion'),
        ),
        migrations.AddField(
            model_name='movimientoficha',
            name='usuario_recepcion_anterior',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_recepcionados_anterior', to='personas.usuarioanterior', verbose_name='Usuario Recepcion Anterior'),
        ),
        migrations.AddField(
            model_name='movimientoficha',
            name='usuario_traspaso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_traspasados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Traspaso'),
        ),
        migrations.AddConstraint(
            model_name='ficha',
            constraint=models.UniqueConstraint(fields=('numero_ficha_sistema', 'establecimiento'), name='unique_ficha_por_establecimiento'),
        ),
    ]
