# Generated by Django 6.0 on 2026-01-06 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0002_historicalmovimientoficha_movimientoficha'),
    ]

    operations = [
        migrations.AddField(
            model_name='ficha',
            name='fecha_mov',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Movimiento'),
        ),
        migrations.AddField(
            model_name='historicalficha',
            name='fecha_mov',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Movimiento'),
        ),
    ]
