# Generated by Django 6.0 on 2026-01-26 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalmovimientoficha',
            name='estado_envio',
            field=models.CharField(blank=True, choices=[('ENVIADO', 'Enviado'), ('RECIBIDO', 'Recibido'), ('EN ESPERA', 'En Espera'), ('TRASPASADO', 'Traspasado'), ('SIN TRASPASO', 'Sin Traspaso')], default='ENVIADO', max_length=50, null=True, verbose_name='Estado de Envío'),
        ),
        migrations.AlterField(
            model_name='historicalmovimientoficha',
            name='estado_recepcion',
            field=models.CharField(blank=True, choices=[('ENVIADO', 'Enviado'), ('RECIBIDO', 'Recibido'), ('EN ESPERA', 'En Espera'), ('TRASPASADO', 'Traspasado'), ('SIN TRASPASO', 'Sin Traspaso')], default='EN ESPERA', max_length=50, null=True, verbose_name='Estado de Recepción'),
        ),
        migrations.AlterField(
            model_name='historicalmovimientoficha',
            name='estado_traspaso',
            field=models.CharField(blank=True, choices=[('ENVIADO', 'Enviado'), ('RECIBIDO', 'Recibido'), ('EN ESPERA', 'En Espera'), ('TRASPASADO', 'Traspasado'), ('SIN TRASPASO', 'Sin Traspaso')], default='SIN TRASPASO', max_length=50, null=True, verbose_name='Estado de Traspaso'),
        ),
        migrations.AlterField(
            model_name='movimientoficha',
            name='estado_envio',
            field=models.CharField(blank=True, choices=[('ENVIADO', 'Enviado'), ('RECIBIDO', 'Recibido'), ('EN ESPERA', 'En Espera'), ('TRASPASADO', 'Traspasado'), ('SIN TRASPASO', 'Sin Traspaso')], default='ENVIADO', max_length=50, null=True, verbose_name='Estado de Envío'),
        ),
        migrations.AlterField(
            model_name='movimientoficha',
            name='estado_recepcion',
            field=models.CharField(blank=True, choices=[('ENVIADO', 'Enviado'), ('RECIBIDO', 'Recibido'), ('EN ESPERA', 'En Espera'), ('TRASPASADO', 'Traspasado'), ('SIN TRASPASO', 'Sin Traspaso')], default='EN ESPERA', max_length=50, null=True, verbose_name='Estado de Recepción'),
        ),
        migrations.AlterField(
            model_name='movimientoficha',
            name='estado_traspaso',
            field=models.CharField(blank=True, choices=[('ENVIADO', 'Enviado'), ('RECIBIDO', 'Recibido'), ('EN ESPERA', 'En Espera'), ('TRASPASADO', 'Traspasado'), ('SIN TRASPASO', 'Sin Traspaso')], default='SIN TRASPASO', max_length=50, null=True, verbose_name='Estado de Traspaso'),
        ),
    ]
