# Generated by Django 6.0.1 on 2026-02-10 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0003_alter_historicalmovimientoficha_estado_envio_and_more'),
        ('personas', '0004_alter_historicalpaciente_fecha_fallecimiento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ficha',
            name='usuario_anterior',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fichas_usuarios_anteriores', to='personas.usuarioanterior', verbose_name='Usuario Anterior'),
        ),
        migrations.AddField(
            model_name='historicalficha',
            name='usuario_anterior',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='personas.usuarioanterior', verbose_name='Usuario Anterior'),
        ),
    ]
