# Generated by Django 6.0 on 2026-01-19 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0003_ficha_fecha_mov_historicalficha_fecha_mov'),
    ]

    operations = [
        migrations.AddField(
            model_name='ficha',
            name='numero_ficha_respaldo',
            field=models.IntegerField(blank=True, null=True, verbose_name='Número de Ficha Respaldo'),
        ),
        migrations.AddField(
            model_name='historicalficha',
            name='numero_ficha_respaldo',
            field=models.IntegerField(blank=True, null=True, verbose_name='Número de Ficha Respaldo'),
        ),
    ]
