# Generated by Django 6.0.1 on 2026-02-10 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0004_ficha_usuario_anterior_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ficha',
            name='rut_anterior',
            field=models.CharField(blank=True, default='SIN RUT', max_length=50, null=True, verbose_name='RUT Anterior del Usuario'),
        ),
        migrations.AddField(
            model_name='historicalficha',
            name='rut_anterior',
            field=models.CharField(blank=True, default='SIN RUT', max_length=50, null=True, verbose_name='RUT Anterior del Usuario'),
        ),
    ]
