# Generated by Django 6.0.1 on 2026-02-10 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0005_ficha_rut_anterior_historicalficha_rut_anterior'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='ficha',
            name='unique_ficha_por_establecimiento',
        ),
        migrations.AlterField(
            model_name='ficha',
            name='rut_anterior',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='RUT Anterior del Usuario'),
        ),
        migrations.AlterField(
            model_name='historicalficha',
            name='rut_anterior',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='RUT Anterior del Usuario'),
        ),
    ]
