# Generated by Django 6.0.1 on 2026-02-11 12:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0006_remove_ficha_unique_ficha_por_establecimiento_and_more'),
        ('establecimientos', '0002_initial'),
        ('personas', '0004_alter_historicalpaciente_fecha_fallecimiento_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimientoMonologoControlado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(choices=[(True, 'Activo'), (False, 'Inactivo')], default=True, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('rut', models.CharField(max_length=50)),
                ('numero_ficha', models.IntegerField()),
                ('fecha_salida', models.DateTimeField()),
                ('usuario_entrega', models.CharField(max_length=50)),
                ('fecha_entrada', models.DateTimeField(blank=True, null=True)),
                ('usuario_entrada', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_traspaso', models.DateTimeField(blank=True, null=True)),
                ('usuario_traspaso', models.CharField(blank=True, max_length=50, null=True)),
                ('observacion_salida', models.TextField(blank=True, null=True)),
                ('observacion_entrada', models.TextField(blank=True, null=True)),
                ('observacion_traspaso', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('E', 'Enviado'), ('R', 'Recibido')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado Por')),
                ('establecimiento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='establecimientos.establecimiento')),
                ('ficha', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clinica.ficha')),
                ('profesional', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='personas.profesional')),
                ('rut_paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='personas.paciente')),
                ('servicio_clinico_destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='establecimientos.servicioclinico')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado Por')),
            ],
            options={
                'verbose_name': 'Movimiento Monologo Controlado',
                'verbose_name_plural': 'Movimientos Monologo Controlados',
            },
        ),
    ]
