# Generated by Django 6.0.1 on 2026-02-11 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0007_movimientomonologocontrolado'),
        ('establecimientos', '0002_initial'),
        ('personas', '0004_alter_historicalpaciente_fecha_fallecimiento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientomonologocontrolado',
            name='profesional_anterior',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='movimientomonologocontrolado',
            name='usuario_entrada_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_recibidos', to='personas.usuarioanterior'),
        ),
        migrations.AddField(
            model_name='movimientomonologocontrolado',
            name='usuario_entrega_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_entregados', to='personas.usuarioanterior'),
        ),
        migrations.AlterField(
            model_name='movimientomonologocontrolado',
            name='ficha',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clinica.ficha'),
        ),
        migrations.AlterField(
            model_name='movimientomonologocontrolado',
            name='profesional',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='personas.profesional'),
        ),
        migrations.AlterField(
            model_name='movimientomonologocontrolado',
            name='rut_paciente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='personas.paciente'),
        ),
        migrations.AlterField(
            model_name='movimientomonologocontrolado',
            name='servicio_clinico_destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='establecimientos.servicioclinico'),
        ),
        migrations.AlterField(
            model_name='movimientomonologocontrolado',
            name='usuario_entrega',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
