# Generated by Django 6.0.1 on 2026-02-11 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0008_movimientomonologocontrolado_profesional_anterior_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientomonologocontrolado',
            name='fecha_salida',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
