# Generated by Django 6.0.1 on 2026-03-03 15:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0009_alter_movimientomonologocontrolado_fecha_salida'),
        ('establecimientos', '0003_alter_servicioclinico_options'),
        ('personas', '0005_alter_prevision_options_alter_profesional_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movimientomonologocontrolado',
            options={'ordering': ['-id'], 'verbose_name': 'Movimiento Monologo Controlado', 'verbose_name_plural': 'Movimientos Monologo Controlados'},
        ),
        migrations.AlterField(
            model_name='movimientomonologocontrolado',
            name='estado',
            field=models.CharField(choices=[('E', 'Enviado'), ('R', 'Recibido'), ('S', 'Sin Paciente')], max_length=1),
        ),
        migrations.AddConstraint(
            model_name='ficha',
            constraint=models.UniqueConstraint(fields=('numero_ficha_sistema', 'establecimiento'), name='unique_ficha_por_establecimiento'),
        ),
    ]
