# Generated by Django 6.0.1 on 2026-03-04 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0010_alter_movimientomonologocontrolado_options_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='ficha',
            name='unique_ficha_por_establecimiento',
        ),
    ]
