# Generated by Django 6.0.1 on 2026-04-01 11:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0011_remove_ficha_unique_ficha_por_establecimiento'),
        ('establecimientos', '0003_alter_servicioclinico_options'),
        ('personas', '0006_alter_historicalpaciente_genero_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='ficha',
            constraint=models.UniqueConstraint(fields=('establecimiento', 'numero_ficha_sistema'), name='unique_ficha_numero_por_establecimiento'),
        ),
    ]
