# Generated by Django 6.0.1 on 2026-04-20 19:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('establecimientos', '0003_alter_servicioclinico_options'),
        ('geografia', '0003_alter_comuna_options'),
        ('personas', '0006_alter_historicalpaciente_genero_and_more'),
        ('respaldos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='respaldoficha',
            name='establecimiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='respaldo_fichas_establecimientos', to='establecimientos.establecimiento', verbose_name='Establecimiento'),
        ),
        migrations.AlterField(
            model_name='respaldoficha',
            name='paciente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='respaldo_fichas_pacientes', to='personas.paciente', verbose_name='Paciente'),
        ),
        migrations.AlterField(
            model_name='respaldoficha',
            name='sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='respaldo_fichas_sectores', to='establecimientos.sector', verbose_name='Sector'),
        ),
        migrations.AlterField(
            model_name='respaldoficha',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='respaldo_fichas_usuarios', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='respaldoficha',
            name='usuario_anterior',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='respaldo_fichas_usuarios_anteriores', to='personas.usuarioanterior', verbose_name='Usuario Anterior'),
        ),
        migrations.AlterField(
            model_name='respaldopaciente',
            name='comuna',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='respaldo_pacientes_comuna', to='geografia.comuna', verbose_name='Comuna'),
        ),
        migrations.AlterField(
            model_name='respaldopaciente',
            name='usuario_anterior',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='respaldo_usuarios_anteriores', to='personas.usuarioanterior', verbose_name='UsuarioAnterior'),
        ),
    ]
