# Generated by Django 6.0 on 2026-01-26 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpaciente',
            name='genero',
            field=models.ForeignKey(blank=True, db_constraint=False, default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='personas.genero', verbose_name='Género'),
        ),
        migrations.AlterField(
            model_name='historicalprofesional',
            name='telefono',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='genero',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pacientes_genero', to='personas.genero', verbose_name='Género'),
        ),
        migrations.AlterField(
            model_name='profesional',
            name='telefono',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Teléfono'),
        ),
    ]
