# Generated by Django 6.0 on 2026-01-05 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0002_genero_historicalgenero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalprofesional',
            name='rut',
            field=models.CharField(max_length=100, verbose_name='R.U.T.'),
        ),
        migrations.AlterField(
            model_name='profesional',
            name='rut',
            field=models.CharField(max_length=100, verbose_name='R.U.T.'),
        ),
    ]
