# Generated by Django 6.0 on 2026-01-05 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0003_alter_historicalprofesional_rut_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalusuarioanterior',
            name='id',
            field=models.IntegerField(blank=True, db_index=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuarioanterior',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='historicalusuarioanterior',
            name='rut',
            field=models.CharField(max_length=100, verbose_name='R.U.T.'),
        ),
        migrations.AlterField(
            model_name='usuarioanterior',
            name='rut',
            field=models.CharField(max_length=100, verbose_name='R.U.T.'),
        ),
    ]
