# Generated by Django 6.0.1 on 2026-02-09 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0003_alter_historicalpaciente_genero_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpaciente',
            name='fecha_fallecimiento',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Fallecimiento'),
        ),
        migrations.AlterField(
            model_name='historicalpaciente',
            name='fecha_nacimiento',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Nacimiento'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='fecha_fallecimiento',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Fallecimiento'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='fecha_nacimiento',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Nacimiento'),
        ),
    ]
