# Generated by Django 6.0.1 on 2026-03-03 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0004_alter_historicalpaciente_fecha_fallecimiento_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prevision',
            options={'ordering': ['nombre'], 'verbose_name': 'Prevision', 'verbose_name_plural': 'Previsiones'},
        ),
        migrations.AlterModelOptions(
            name='profesional',
            options={'ordering': ['nombres'], 'verbose_name': 'Profesional', 'verbose_name_plural': 'Profesionales'},
        ),
        migrations.AlterField(
            model_name='historicalpaciente',
            name='fecha_fallecimiento',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Fallecimiento'),
        ),
        migrations.AlterField(
            model_name='historicalpaciente',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='fecha_fallecimiento',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Fallecimiento'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento'),
        ),
    ]
