# Generated by Django 6.0 on 2026-01-05 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0004_historicalusuarioanterior_id_usuarioanterior_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalprevision',
            name='codigo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prevision',
            name='codigo',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
