# Generated by Django 6.0.1 on 2026-03-06 17:40

import django.db.models.deletion
import personas.models.pacientes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0005_alter_prevision_options_alter_profesional_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpaciente',
            name='genero',
            field=models.ForeignKey(blank=True, db_constraint=False, default=personas.models.pacientes.get_genero_no_informado, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='personas.genero', verbose_name='Género'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='genero',
            field=models.ForeignKey(blank=True, default=personas.models.pacientes.get_genero_no_informado, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pacientes_genero', to='personas.genero', verbose_name='Género'),
        ),
    ]
