# Generated by Django 6.0 on 2026-01-05 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0006_historicalpaciente_paciente'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpaciente',
            name='id_anterior',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID Anterior'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='id_anterior',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID Anterior'),
        ),
    ]
