# Generated by Django 6.0 on 2026-01-06 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0007_historicalpaciente_id_anterior_paciente_id_anterior'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpaciente',
            name='estado_civil',
            field=models.CharField(choices=[('I', 'No Informado'), ('S', 'Soltero(a)'), ('C', 'Casado(a)'), ('D', 'Divorciado(a)'), ('V', 'Viudo(a)'), ('O', 'Conviviente')], default='NO INFORMADO', max_length=20, verbose_name='Estado Civil'),
        ),
        migrations.AlterField(
            model_name='historicalpaciente',
            name='sexo',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=10, verbose_name='Sexo'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='estado_civil',
            field=models.CharField(choices=[('I', 'No Informado'), ('S', 'Soltero(a)'), ('C', 'Casado(a)'), ('D', 'Divorciado(a)'), ('V', 'Viudo(a)'), ('O', 'Conviviente')], default='NO INFORMADO', max_length=20, verbose_name='Estado Civil'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='sexo',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=10, verbose_name='Sexo'),
        ),
    ]
