# Generated by Django 6.0 on 2026-01-07 02:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0008_alter_historicalpaciente_estado_civil_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpaciente',
            name='genero',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='personas.genero', verbose_name='Género'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='genero',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pacientes_genero', to='personas.genero', verbose_name='Género'),
        ),
    ]
