# Generated by Django 6.0 on 2026-01-19 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0009_alter_historicalpaciente_genero_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpaciente',
            name='estado_civil',
            field=models.CharField(choices=[('I', 'NO INFORMADO'), ('S', 'SOLTERO(A)'), ('C', 'CASADO(A)'), ('D', 'DIVORCIADO(A)'), ('V', 'VIUDO(A)'), ('O', 'CONVIVIENTE')], default='NO INFORMADO', max_length=20, verbose_name='Estado Civil'),
        ),
        migrations.AlterField(
            model_name='historicalpaciente',
            name='sexo',
            field=models.CharField(choices=[('NO INFORMADO', 'NO INFORMADO'), ('M', 'MASCULINO'), ('F', 'FEMENINO')], default='NO INFORMADO', max_length=50, verbose_name='Sexo'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='estado_civil',
            field=models.CharField(choices=[('I', 'NO INFORMADO'), ('S', 'SOLTERO(A)'), ('C', 'CASADO(A)'), ('D', 'DIVORCIADO(A)'), ('V', 'VIUDO(A)'), ('O', 'CONVIVIENTE')], default='NO INFORMADO', max_length=20, verbose_name='Estado Civil'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='sexo',
            field=models.CharField(choices=[('NO INFORMADO', 'NO INFORMADO'), ('M', 'MASCULINO'), ('F', 'FEMENINO')], default='NO INFORMADO', max_length=50, verbose_name='Sexo'),
        ),
    ]
